# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import core_pb2 as core__pb2


class CoreJSStub(object):
    """The core service for executing on js
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Execute = channel.unary_stream(
                '/CoreJS/Execute',
                request_serializer=core__pb2.InputData.SerializeToString,
                response_deserializer=core__pb2.OutputData.FromString,
                )


class CoreJSServicer(object):
    """The core service for executing on js
    """

    def Execute(self, request, context):
        """executes the given code with the given data and returns the given data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoreJSServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Execute': grpc.unary_stream_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=core__pb2.InputData.FromString,
                    response_serializer=core__pb2.OutputData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CoreJS', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CoreJS(object):
    """The core service for executing on js
    """

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/CoreJS/Execute',
            core__pb2.InputData.SerializeToString,
            core__pb2.OutputData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
